version: '3'

services:

  app:
    image: vectorzhao/links-shorter-tgbot:latest
    container_name: links-shorter-tgbot
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
