name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "links-shorter-tgbot" #Must be unique in Heroku
          heroku_email: "kissuget@gmail.com"
          usedocker: true
          docker_build_args: |
            API_URL
            API_KEY
            BOT_TOKEN
            AUTH_USERS
        env:
          API_URL: ${{ secrets.API_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          AUTH_USERS: ${{ secrets.AUTH_USERS }}
